parameters:
    secret: replace_with_secret
    encryption_key: replace_encryption_key
    locale: en
    ip_whitelist:
        - 192.168.33.1
        - 127.0.0.1
        - ::1
        - 185.16.20.0/22
        - 192.95.80.0/20
        - 77.95.98.128/25
        - 31.221.51.230/32
        - 206.252.201.210/32
        - 96.251.72.217/32
        - 66.96.193.104/32
        - 80.227.113.90/32
        - 201.216.212.53/32
        - 177.8.170.226/32
        - 151.236.200.4/32

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    admin_directory: admin
    asset_version: src #[deploytool]