doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        server_version: 5.6
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false
            #AppCoreBundle: ~
            #SonataUserBundle: ~
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Migrations
doctrine_migrations:
    dir_name: %kernel.root_dir%/../var/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Migrations

# Extensions
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            softdeleteable: true
            loggable: true
            sluggable: true
            sortable: true