imports:
    - { resource: config.yml }
    - { resource: parameters_local.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_local.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    validation:
        cache: framework.cache.apcu
    serializer:
        cache: framework.cache.apcu

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    orm:
        metadata_cache_driver: array
        result_cache_driver: array
        query_cache_driver: array

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
