security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        default_user_provider:
            entity:
                class: AppCoreBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~

        admin:
            pattern:            ^/%admin_directory%(.*)
            context:            user
            form_login:
                provider:       default_user_provider
                login_path:     /%admin_directory%/login
                use_forward:    false
                check_path:     /%admin_directory%/login_check
                failure_path:   null
                always_use_default_target_path: true
                default_target_path: /%admin_directory%/dashboard
            logout:
                path:           /%admin_directory%/logout
            anonymous:          ~

        api:
            pattern: ^/api(.*)
            anonymous: ~
            stateless: ~
            guard:
                authenticators:
                    - api.security.authenticator.credentials_authenticator
                    - api.security.authenticator.jwt_authenticator
                entry_point: 'api.security.authenticator.jwt_authenticator'

    access_control:
        - { path: ^/%admin_directory%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_directory%/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_directory%/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_directory%/(.*), role: ROLE_ADMIN }
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/(.*), role: IS_AUTHENTICATED_FULLY }