services:
    admin.controller.security:
        class: App\AdminBundle\Controller\SecurityController
        arguments:
            - '@security.authentication_utils'
            - '@templating'

    admin.listener.ip_whitelist:
        class: App\AdminBundle\EventListener\IpWhitelistListener
        arguments:
            - "%admin_directory%"
            - "%ip_whitelist%"
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    admin.user:
        class: App\AdminBundle\Admin\UserAdmin
        arguments: [~, App\CoreBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users, group: User management }