services:
    api.security.jwt_authenticator:
        class: App\ApiBundle\Security\JWTAuthenticator
        arguments:
            - '@core.security.jwt_manager'
            - '@doctrine.orm.entity_manager'