services:
    core.repository.user:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\CoreBundle\Entity\User

    core.security.jwt_manager:
        class: App\CoreBundle\Security\JWT\FirebaseJWTManager
        arguments:
            - '%secret%'

    core.listener.cache:
        class: App\CoreBundle\EventListener\CacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response }