version: "3"
services:
    web:
        container_name: web
        image: nginx:alpine
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - ../../:/var/www
            - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./web/www.conf:/etc/nginx/conf.d/www.conf:ro
        working_dir: /var/www/source/symfony
        command: bash -c "cd /var/www/tools/docker/web && chmod +x ./generate-ssl && ./generate-ssl && nginx -g 'daemon off;'"

    php:
        container_name: php
        build:
            args:
                with_xdebug: 'true'
                php_version: __php_version__
            context: ./php
        image: php.__hostname__
        volumes:
            - ../../:/var/www
        working_dir: /var/www/source/symfony
        command: bash -c "cd /var/www/tools/docker/php && chmod +x ./symfony-init && ./symfony-init && php-fpm --nodaemonize"
