version: "3"
services:
    apache:
        build:
            context: .
        container_name: apache
        image: __image__
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "../../:/var/www/html"
            - "~/composer-cache/:/root/.composer/cache" #optional
#        links:
#            - mysql
#    mysql:
#        image: mysql
#        volumes:
#            - "./sql:/docker-entrypoint-initdb.d"
#        environment:
#            - MYSQL_DATABASE=database_name
#            - MYSQL_ALLOW_EMPTY_PASSWORD=yes