version: "3"
services:
    web:
        container_name: web
        build:
            context: ./web
        image: web.__hostname__
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../../:/var/www
        working_dir: /var/www/source/symfony
        command: bash -c "cd /var/www/tools/docker/web && chmod +x ./generate-ssl && ./generate-ssl && nginx -g 'daemon off;'"

    php:
        container_name: php
        build:
            args:
                with_libsodium: 'false'
                with_xdebug: 'true'
                php_version: __php_version__
            context: ./php
        image: php.__hostname__
        volumes:
            - ../../:/var/www
        working_dir: /var/www/source/symfony
        command: bash -c "cd /var/www/tools/docker/php && chmod +x ./symfony-init && ./symfony-init && php-fpm --nodaemonize"
